namespace Maui.Health.Enums;

/// <summary>
/// Types of physical activities/workouts tracked by health platforms
/// Based on HKWorkoutActivityType (iOS) and ExerciseSessionRecord types (Android)
/// </summary>
public enum ActivityType
{
    Unknown = 0,

    AmericanFootball = 1,
    Archery = 2,
    AustralianFootball = 3,
    Badminton = 4,
    Barre = 5,
    Baseball = 6,
    Basketball = 7,
    BootCamp = 8,
    Bowling = 9,
    Boxing = 10,
    Calisthenics = 11,
    Climbing = 12,
    Cooldown = 13,
    CoreTraining = 14,
    Cricket = 15,
    CrossTraining = 16,
    Curling = 17,
    Cycling = 18,
    CyclingStationary = 19,
    Dance = 20,
    DanceInspiredTraining = 21,
    DiscSports = 22,
    Elliptical = 23,
    ExerciseClass = 24,
    EquestrianSports = 25,
    Fencing = 26,
    Fishing = 27,
    FitnessGaming = 28,
    FrisbeeDisc = 29,
    Golf = 30,
    Gymnastics = 31,
    Handball = 32,
    HandCycling = 33,
    HighIntensityIntervalTraining = 34,
    Hiking = 35,
    Hockey = 36,
    Hunting = 37,
    JumpRope = 38,
    Kickboxing = 39,
    Lacrosse = 40,
    MartialArts = 41,
    MindAndBody = 42,
    MixedCardio = 43,
    MixedMetabolicCardioTraining = 44,
    PaddleSports = 45,
    Paragliding = 46,
    Pickleball = 47,
    Pilates = 48,
    Play = 49,
    PreparationAndRecovery = 50,
    Racquetball = 51,
    Rowing = 52,
    Rugby = 53,
    Running = 54,
    Sailing = 55,
    SkatingSports = 56,
    Skiing = 57,
    Snowboarding = 58,
    SnowSports = 59,
    Soccer = 60,
    Softball = 61,
    Squash = 62,
    StairClimbing = 63,
    Stairs = 64,
    StepTraining = 65,
    StrengthTraining = 66,
    Stretching = 67,
    SurfingSports = 68,
    SwimBikeRun = 69,
    Swimming = 70,
    TableTennis = 71,
    TaiChi = 72,
    Tennis = 73,
    TrackAndField = 74,
    Transition = 75,
    UnderwaterDiving = 76,
    Volleyball = 77,
    Walking = 78,
    WaterFitness = 79,
    WaterPolo = 80,
    WaterSports = 81,
    Weightlifting = 82,
    WheelchairRunPace = 83,
    WheelchairWalkPace = 84,
    Wrestling = 85,
    Yoga = 86
}
